In [1]:
import torch

In [2]:
torch.__version__

'1.9.0+cu102'

In [4]:
# tensor는 torch의 기본 자료형
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [5]:
# 랭크 늘리기
x = torch.unsqueeze(x, 0)  # 가장 바깥의 차원을 늘려줘
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [6]:
# 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [7]:
# 랭크의 형태 바꾸기-1
a = torch.tensor([[1,2,3],[4,5,6]])
print(a)
print("Size:", a.size())
print("Shape:", a.shape)
print("랭크(차원):", a.ndimension())


tensor([[1, 2, 3],
        [4, 5, 6]])
Size: torch.Size([2, 3])
Shape: torch.Size([2, 3])
랭크(차원): 2


In [8]:
# 랭크의 형태 바꾸기-2
a = a.view(6)
print(a)
print("Size:", a.size())
print("Shape:", a.shape)
print("랭크(차원):", a.ndimension())

tensor([1, 2, 3, 4, 5, 6])
Size: torch.Size([6])
Shape: torch.Size([6])
랭크(차원): 1


In [9]:
# 랭크의 형태 바꾸기-3
a = a.view(3, 2)
print(a)
print("Size:", a.size())
print("Shape:", a.shape)
print("랭크(차원):", a.ndimension())

tensor([[1, 2],
        [3, 4],
        [5, 6]])
Size: torch.Size([3, 2])
Shape: torch.Size([3, 2])
랭크(차원): 2


In [10]:
# 랭크의 형태 바꾸기-4
a = a.view(1, 2, 3)
print(a)
print("Size:", a.size())
print("Shape:", a.shape)
print("랭크(차원):", a.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6]]])
Size: torch.Size([1, 2, 3])
Shape: torch.Size([1, 2, 3])
랭크(차원): 3


In [11]:
# 랭크의 형태 바꾸기-5
a = a.view(6, 1)
print(a)
print("Size:", a.size())
print("Shape:", a.shape)
print("랭크(차원):", a.ndimension())

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Size: torch.Size([6, 1])
Shape: torch.Size([6, 1])
랭크(차원): 2


In [13]:
try:
  x = x.view(2, 4)  # 9 -> 8
  print(x)
  print("Size:", x.size())
  print("Shape:", x.shape)
  print("랭크(차원):", x.ndimension())
except Exception as e:
  print("[예외발생]")
  print(e)

[예외발생]
shape '[2, 4]' is invalid for input of size 9
